[package]
name = "soar"
version = "0.1.0"
authors = ["Sam Scott <sam.scott89@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Build a generic service-oriented architecture using actix."

[dependencies]
actix = "0.7.6"
env_logger = "0.5.13"
futures = "0.1.25"
log = "0.4.6"
query_interface = "0.3.5"
actix-web = "0.7.13"
serde = "1.0.80"
failure = "0.1.3"
serde_derive = "1.0.80"
